/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/qB6jJ9bbUo6
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import {
  SelectValue,
  SelectTrigger,
  SelectItem,
  SelectContent,
  Select,
} from "@/components/ui/select";
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";
import { Slider, Button } from "@nextui-org/react";
import { Send } from "lucide-react";

export function Comment() {
  return (
    <div className="mx-auto max-w-2xl space-y-8 py-8">
      <div className="space-y-2">
        <h2 className="text-2xl font-bold">User Comment</h2>
        <p className="text-gray-500 dark:text-gray-400">
          Share your thoughts and comment with us.
        </p>
      </div>
      <form className="grid gap-4">
        <Textarea
          className="min-h-[120px]"
          placeholder="Write your feedback here..."
        />
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2 flex-1 pr-20">
            <Slider
              size="sm"
              step={0.5}
              color="primary"
              label="Score"
              showSteps={true}
              maxValue={5}
              minValue={0}
              defaultValue={0.5}
              className="max-w-md"
            />
          </div>
          <Button variant="ghost" color="primary" startContent={<Send />}>
            Submit Comment
          </Button>
        </div>
      </form>
      <div className="space-y-6">
        <div className="flex items-start gap-4">
          <Avatar className="h-10 w-10 border">
            <AvatarImage alt="@shadcn" src="/placeholder-user.jpg" />
            <AvatarFallback>AC</AvatarFallback>
          </Avatar>
          <div className="flex-1 space-y-1">
            <div className="flex items-center justify-between">
              <div className="font-medium">Alicia Clark</div>
              <div className="flex items-center gap-1">
                <StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                <StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                <StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                <StarIcon className="w-4 h-4 fill-gray-100 stroke-gray-500 dark:fill-gray-800 dark:stroke-gray-400" />
                <StarIcon className="w-4 h-4 fill-gray-100 stroke-gray-500 dark:fill-gray-800 dark:stroke-gray-400" />
              </div>
              <time className="text-xs text-gray-500 dark:text-gray-400">
                2 days ago
              </time>
            </div>
            <p>
              The new features are really helpful for our team. The deployment
              process is much smoother now.
            </p>
          </div>
        </div>
        <div className="flex items-start gap-4">
          <Avatar className="h-10 w-10 border">
            <AvatarImage alt="@shadcn" src="/placeholder-user.jpg" />
            <AvatarFallback>JD</AvatarFallback>
          </Avatar>
          <div className="flex-1 space-y-1">
            <div className="flex items-center justify-between">
              <div className="font-medium">John Doe</div>
              <div className="flex items-center gap-1">
                <StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                <StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                <StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                <StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                <StarIcon className="w-4 h-4 fill-gray-100 stroke-gray-500 dark:fill-gray-800 dark:stroke-gray-400" />
              </div>
              <time className="text-xs text-gray-500 dark:text-gray-400">
                1 week ago
              </time>
            </div>
            <p>
              The new dashboard is really intuitive and easy to use. I am able
              to find the information I need much faster.
            </p>
          </div>
        </div>
        <div className="flex items-start gap-4">
          <Avatar className="h-10 w-10 border">
            <AvatarImage alt="@shadcn" src="/placeholder-user.jpg" />
            <AvatarFallback>ES</AvatarFallback>
          </Avatar>
          <div className="flex-1 space-y-1">
            <div className="flex items-center justify-between">
              <div className="font-medium">Emily Simmons</div>
              <div className="flex items-center gap-1">
                <StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                <StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                <StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                <StarIcon className="w-4 h-4 fill-gray-100 stroke-gray-500 dark:fill-gray-800 dark:stroke-gray-400" />
                <StarIcon className="w-4 h-4 fill-gray-100 stroke-gray-500 dark:fill-gray-800 dark:stroke-gray-400" />
              </div>
              <time className="text-xs text-gray-500 dark:text-gray-400">
                3 weeks ago
              </time>
            </div>
            <p>
              I am really impressed with the customer support team. They were
              able to resolve my issue quickly and efficiently.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

function StarIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  );
}
